name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu çek
      uses: actions/checkout@v3

    - name: Node.js kurulumu
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Bağımlılıkları yükle
      run: npm install

    - name: Testleri çalıştır
      run: npm test
